app:
  env: local
  port: 8081
  app_name: sp_blog
  app_url: http://localhost
log:
  level: info # 日志等级
  root_dir: ./logs # 日志根目录
  filename: app.log # 日志文件名称
  format: json # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩
database:
  driver: mysql # 数据库驱动
  host: mysql.starpearl.cn # 域名
  port: 3306 # 端口号
  database: starpearl_blog # 数据库名称
  username: starpearl # 用户名
  password: Starpearl0110 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
jwt:
  secret: hf8DSnoTIi3MdxqxkrKdoKLtCqLq0KsNHIWmJ7rqUbYEHGU0ujTN3v4WPxHznccO
  jwt_ttl: 44400
  jwt_blacklist_grace_period: 0
  refresh_grace_period: 12800
redis:
  host: redis.starpearl.cn
  port: 6379
  db: 0
  username: starpearl
  password: Starpearl0110
storage:
  default: local # 默认驱动
  disks:
    local:
      root_dir: ./storage/app # 本地存储根目录
      app_url: http://localhost:8081/storage # 本地图片 url 前部
